[unstable]
codegen-backend = true

[target.x86_64-unknown-linux-gnu]
linker = "/bin/clang"
rustflags = [
	"-Clink-arg=-fuse-ld=/bin/mold",
	"-Ctarget-cpu=native",
]

[target.nightly-x86_64-unknown-linux-gnu]
rustflags = ["-Zthreads=4", "-Ztrack-diagnostics", "-Zpanic-abort-tests"]
linker = "clang"
codegen-backend = "cranelift"

[alias]
t = "nextest run"
a = "cargo-add"
f = "fix --allow-dirty --allow-no-vcs"
fc = "clippy --fix --allow-dirty --allow-no-vcs"
