[target.x86_64-unknown-linux-gnu]
linker = "/bin/clang"
rustflags = [
	"-Clink-arg=-fuse-ld=/bin/mold",
	"-Ctarget-cpu=native",
	# "-Znext-solver",
	# "-Zthreads=4"
]

[target.nightly-x86_64-unknown-linux-gnu]
rustflags = ["-Zthreads=4", "-Ztrack-diagnostics", "-Zpanic-abort-tests"]
linker = "clang"
codegen-backend = "cranelift"

[build]
rustc-wrapper = "/usr/bin/sccache"

[alias]
f = "fix --allow-dirty --allow-no-vcs"
fc = "clippy --fix --allow-dirty --allow-no-vcs"
t = "nextest run"
a = "cargo-add"

[unstable]
codegen-backend = true
