[target.x86_64-unknown-linux-gnu]
linker = "/bin/clang"
rustflags = ["-Clink-arg=-fuse-ld=/bin/mold", "-Ctarget-cpu=native"]

[build]
rustc-wrapper = "/usr/bin/sccache"

[alias]
f = "fix --allow-dirty --allow-no-vcs"
fc = "clippy --fix --allow-dirty --allow-no-vcs"
t = "nextest run"

# [unstable]
# codegen-backend = true
#
# [profile.dev]
# codegen-backend = "cranelift"
